language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-software-properties
  - sudo add-apt-repository -y ppa:xnox/backports
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq libnih
  - sudo apt-get install -qq autoconf automake autopoint libtool  debhelper dh-autoreconf pkg-config perl expat
before_script:
  - autoreconf -f -i
  - ./configure
  - make -j4 -l
script:
  - make check
